/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_clrpalet_Source
#define SOM_Module_clrpalet_Source
#endif
#define ColorPalette_Class_Source
#define M_ColorPalette_Class_Source

#include "clrpalet.ih"


SOM_Scope BOOL  SOMLINK clrp_SetEditDlgHandle(ColorPalette *somSelf, 
                                              HWND hwndEditDlg)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_SetEditDlgHandle");

    /* Return statement to be customized: */
    return;
}

SOM_Scope HWND  SOMLINK clrp_QueryEditDlgHandle(ColorPalette *somSelf)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_QueryEditDlgHandle");

    /* Return statement to be customized: */
    return;
}

/*
 * NOTE: 'in', not 'inout': the original CSC passed the array pointer
 *     * directly (caller-owned buffer, contents filled out when non-NULL).
 *     * 'inout' would make sc emit 'PPOINTL*' - an extra indirection level
 *     * that neither the original callers nor StarColorPalette expect.
 */

SOM_Scope BOOL  SOMLINK clrp_QuerySampleShape(ColorPalette *somSelf, 
                                              PPOINTL pPoints, 
                                              PULONG pcPoints)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_QuerySampleShape");

    /* Return statement to be customized: */
    return;
}

SOM_Scope void  SOMLINK clrp_wpPaintCell(ColorPalette *somSelf, 
                                         PCELL pCell, HPS hps, 
                                         PRECTL prcl, BOOL fHilite)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_wpPaintCell");

    ColorPalette_parent_WPColorPalette_wpPaintCell(somSelf, pCell, 
                                                   hps, prcl, 
                                                   fHilite);
}

SOM_Scope BOOL  SOMLINK clrp_wpEditCell(ColorPalette *somSelf, 
                                        PCELL pCell, HWND hwndPal)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_wpEditCell");

    return (ColorPalette_parent_WPColorPalette_wpEditCell(somSelf, 
                                                          pCell, 
                                                          hwndPal));
}

SOM_Scope BOOL  SOMLINK clrp_wpRedrawCell(ColorPalette *somSelf, 
                                          PCELL pCell)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_wpRedrawCell");

    return (ColorPalette_parent_WPColorPalette_wpRedrawCell(somSelf, 
                                                            pCell));
}

SOM_Scope BOOL  SOMLINK clrp_wpSetup(ColorPalette *somSelf, PSZ pszSetupString)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_wpSetup");

    return (ColorPalette_parent_WPColorPalette_wpSetup(somSelf, 
                                                       pszSetupString));
}

SOM_Scope void  SOMLINK clrp_wpSelectCell(ColorPalette *somSelf, 
                                          HWND hwndPal, PCELL pCell)
{
    ColorPaletteData *somThis = ColorPaletteGetData(somSelf);
    ColorPaletteMethodDebug("ColorPalette","clrp_wpSelectCell");

    ColorPalette_parent_WPColorPalette_wpSelectCell(somSelf, 
                                                    hwndPal, 
                                                    pCell);
}


SOM_Scope void  SOMLINK clrpM_wpclsInitData(M_ColorPalette *somSelf)
{
    /* M_ColorPaletteData *somThis = M_ColorPaletteGetData(somSelf); */
    M_ColorPaletteMethodDebug("M_ColorPalette","clrpM_wpclsInitData");

    M_ColorPalette_parent_M_WPColorPalette_wpclsInitData(somSelf);
}

SOM_Scope ULONG  SOMLINK clrpM_wpclsQueryIconData(M_ColorPalette *somSelf, 
                                                  PICONINFO pIconInfo)
{
    /* M_ColorPaletteData *somThis = M_ColorPaletteGetData(somSelf); */
    M_ColorPaletteMethodDebug("M_ColorPalette","clrpM_wpclsQueryIconData");

    return (M_ColorPalette_parent_M_WPColorPalette_wpclsQueryIconData(somSelf, 
                                                                      pIconInfo));
}

SOM_Scope ULONG  SOMLINK clrpM_wpclsQueryStyle(M_ColorPalette *somSelf)
{
    /* M_ColorPaletteData *somThis = M_ColorPaletteGetData(somSelf); */
    M_ColorPaletteMethodDebug("M_ColorPalette","clrpM_wpclsQueryStyle");

    return (M_ColorPalette_parent_M_WPColorPalette_wpclsQueryStyle(somSelf));
}

