/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_clrstar_Source
#define SOM_Module_clrstar_Source
#endif
#define StarColorPalette_Class_Source

#include "clrstar.ih"


SOM_Scope BOOL  SOMLINK clrs_QuerySampleShape(StarColorPalette *somSelf, 
                                              PPOINTL pPoints, 
                                              PULONG pcPoints)
{
    /* StarColorPaletteData *somThis = StarColorPaletteGetData(somSelf); */
    StarColorPaletteMethodDebug("StarColorPalette","clrs_QuerySampleShape");

    return (StarColorPalette_parent_ColorPalette_QuerySampleShape(somSelf, 
                                                                  pPoints, 
                                                                  pcPoints));
}

