
/*
 * This file was generated by the SOM Compiler.
 * FileName: h\clrpalet.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * clrpalet.idl - ColorPalette interface definition.
 * 
 * Converted from the SOM 1.0 precompiler format (CLRPALET.SC, produced by
 * 'spc' 1.22 / 'emitcsc' 1.10) to SOM IDL for the modern SOM compiler (sc).
 * 
 * Original class:
 *   IBM Corporation, 1992/1993 - Named Color Palette WPS sample.
 *   ColorPalette = a WPColorPalette subclass: a palette of named colors
 *   that can be dragged and dropped like the system color palette, with a
 *   custom color-editing dialog backed by the ColorWheel control that this
 *   DLL also registers.  Can replace the system WPColorPalette class via
 *   WinReplaceObjectClass.
 * 
 * Conversion notes (full story in README.md):
 *   - 'class:'/'parent:' syntax        -> 'interface X : Parent'
 *   - 'data:' section                  -> instance variables inside the
 *                                         implementation block
 *   - 'override x, class;'             -> metaclass interface M_ColorPalette
 *                                         with its own override list
 *   - overrides use the SOM IDL 'methodname: override;' statement form
 *   - wpSelectCell is now overridden NORMALLY: Toolkit 4.5 declares it as a
 *     public released method of WPPalette (wppalet.idl:47-48) and
 *     WPColorPalette already overrides it (wpclrpal.idl:59).  The 1993 code
 *     had to install the override at runtime (_somOverrideSMethod) and call
 *     the parent through _somFindMethod because the method was then
 *     undocumented; both hacks are gone.
 *   - C.ph passthru IDs -> h\clrpids.h (sc does not emit .ph)
 *   - C.ih passthru content (globals, COLORPICKDATA, forward decls) moved
 *     to the top of src\clrpalet.c
 */


#ifndef SOM_ColorPalette_h
#define SOM_ColorPalette_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef ColorPalette
#define ColorPalette SOMObject
#endif
/*
 *  New methods (release order)
 */
#include <wpclrpal.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_WPPalette
    #define M_WPPalette SOMObject
#endif /* M_WPPalette */
#ifndef M_WPColorPalette
    #define M_WPColorPalette SOMObject
#endif /* M_WPColorPalette */
#ifndef M_ColorPalette
    #define M_ColorPalette SOMObject
#endif /* M_ColorPalette */

/*
 * End of bindings for IDL types.
 */

#define ColorPalette_MajorVersion 1
#define ColorPalette_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define ColorPaletteNewClass c
#pragma linkage(c, system)
#define ColorPaletteClassData d
#define ColorPaletteCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define ColorPalette_classObj ColorPaletteClassData.classObject
#define _ColorPalette ColorPalette_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK ColorPaletteNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(ColorPaletteNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct ColorPaletteClassDataStructure {
	SOMClass *classObject;
	somMToken SetEditDlgHandle;
	somMToken QueryEditDlgHandle;
	somMToken QuerySampleShape;
} SOMDLINK ColorPaletteClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct ColorPaletteCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK ColorPaletteCClassData;

/*
 * New and Renew macros for ColorPalette
 */
#define ColorPaletteNew() \
   ( _ColorPalette ? \
	_somNew(_ColorPalette) \
	: ( ColorPaletteNewClass(\
		ColorPalette_MajorVersion, \
		ColorPalette_MinorVersion),\
	   _somNew(_ColorPalette)))
#define ColorPaletteRenew(buf) \
   ( _ColorPalette ? \
	_somRenew(_ColorPalette, buf) \
	: ( ColorPaletteNewClass(\
		ColorPalette_MajorVersion, \
		ColorPalette_MinorVersion),\
	   _somRenew(_ColorPalette, buf)))

/*
 * Override method: wpPaintCell
 */
#define ColorPalette_wpPaintCell(somSelf,pCell,hps,prcl,fHilite) \
	WPPalette_wpPaintCell(somSelf,pCell,hps,prcl,fHilite)

/*
 * Override method: wpEditCell
 */
#define ColorPalette_wpEditCell(somSelf,pCell,hwndPal) \
	WPPalette_wpEditCell(somSelf,pCell,hwndPal)

/*
 * Override method: wpRedrawCell
 */
#define ColorPalette_wpRedrawCell(somSelf,pCell) \
	WPPalette_wpRedrawCell(somSelf,pCell)

/*
 * Override method: wpSetup
 */
#define ColorPalette_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpSelectCell
 */
#define ColorPalette_wpSelectCell(somSelf,hwndPal,pCell) \
	WPPalette_wpSelectCell(somSelf,hwndPal,pCell)

/*
 * New Method: SetEditDlgHandle
 */
typedef BOOL   SOMLINK somTP_ColorPalette_SetEditDlgHandle(ColorPalette *somSelf, 
		HWND hwndEditDlg);
#pragma linkage(somTP_ColorPalette_SetEditDlgHandle, system)
typedef somTP_ColorPalette_SetEditDlgHandle *somTD_ColorPalette_SetEditDlgHandle;
#define somMD_ColorPalette_SetEditDlgHandle "::ColorPalette::SetEditDlgHandle"
#define ColorPalette_SetEditDlgHandle(somSelf,hwndEditDlg) \
    (SOM_Resolve(somSelf, ColorPalette, SetEditDlgHandle) \
	(somSelf,hwndEditDlg))
#ifndef SOMGD_SetEditDlgHandle
    #if (defined(_SetEditDlgHandle) || defined(__SetEditDlgHandle))
        #undef _SetEditDlgHandle
        #undef __SetEditDlgHandle
        #define SOMGD_SetEditDlgHandle 1
    #else
        #define _SetEditDlgHandle ColorPalette_SetEditDlgHandle
    #endif /* _SetEditDlgHandle */
#endif /* SOMGD_SetEditDlgHandle */

/*
 * New Method: QueryEditDlgHandle
 */
typedef HWND   SOMLINK somTP_ColorPalette_QueryEditDlgHandle(ColorPalette *somSelf);
#pragma linkage(somTP_ColorPalette_QueryEditDlgHandle, system)
typedef somTP_ColorPalette_QueryEditDlgHandle *somTD_ColorPalette_QueryEditDlgHandle;
#define somMD_ColorPalette_QueryEditDlgHandle "::ColorPalette::QueryEditDlgHandle"
#define ColorPalette_QueryEditDlgHandle(somSelf) \
    (SOM_Resolve(somSelf, ColorPalette, QueryEditDlgHandle) \
	(somSelf))
#ifndef SOMGD_QueryEditDlgHandle
    #if (defined(_QueryEditDlgHandle) || defined(__QueryEditDlgHandle))
        #undef _QueryEditDlgHandle
        #undef __QueryEditDlgHandle
        #define SOMGD_QueryEditDlgHandle 1
    #else
        #define _QueryEditDlgHandle ColorPalette_QueryEditDlgHandle
    #endif /* _QueryEditDlgHandle */
#endif /* SOMGD_QueryEditDlgHandle */

/*
 * New Method: QuerySampleShape
 */
typedef BOOL   SOMLINK somTP_ColorPalette_QuerySampleShape(ColorPalette *somSelf, 
		PPOINTL pPoints, 
		PULONG pcPoints);
#pragma linkage(somTP_ColorPalette_QuerySampleShape, system)
typedef somTP_ColorPalette_QuerySampleShape *somTD_ColorPalette_QuerySampleShape;
/*
 *  NOTE: 'in', not 'inout': the original CSC passed the array pointer
 *      * directly (caller-owned buffer, contents filled out when non-NULL).
 *      * 'inout' would make sc emit 'PPOINTL*' - an extra indirection level
 *      * that neither the original callers nor StarColorPalette expect.
 */
#define somMD_ColorPalette_QuerySampleShape "::ColorPalette::QuerySampleShape"
#define ColorPalette_QuerySampleShape(somSelf,pPoints,pcPoints) \
    (SOM_Resolve(somSelf, ColorPalette, QuerySampleShape) \
	(somSelf,pPoints,pcPoints))
#ifndef SOMGD_QuerySampleShape
    #if (defined(_QuerySampleShape) || defined(__QuerySampleShape))
        #undef _QuerySampleShape
        #undef __QuerySampleShape
        #define SOMGD_QuerySampleShape 1
    #else
        #define _QuerySampleShape ColorPalette_QuerySampleShape
    #endif /* _QuerySampleShape */
#endif /* SOMGD_QuerySampleShape */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define ColorPalette_wpDragCell WPPalette_wpDragCell
#define ColorPalette_wpQueryPaletteHelp WPPalette_wpQueryPaletteHelp
#define ColorPalette_wpSetupOnce WPObject_wpSetupOnce
#define ColorPalette_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define ColorPalette_wpInitData WPObject_wpInitData
#define ColorPalette_somDefaultInit SOMObject_somDefaultInit
#define ColorPalette_somDestruct SOMObject_somDestruct
#define ColorPalette_wpSetupCell WPPalette_wpSetupCell
#define ColorPalette_wpQueryPaletteInfo WPPalette_wpQueryPaletteInfo
#define ColorPalette_wpSetPaletteInfo WPPalette_wpSetPaletteInfo
#define ColorPalette_wpPaintPalette WPPalette_wpPaintPalette
#define ColorPalette_wpInitCellStructs WPPalette_wpInitCellStructs
#define ColorPalette_wpSaveCellData WPPalette_wpSaveCellData
#define ColorPalette_wpRestoreCellData WPPalette_wpRestoreCellData
#define ColorPalette_wpFreeCellData WPPalette_wpFreeCellData
#define ColorPalette_wpUnInitData WPObject_wpUnInitData
#define ColorPalette_wpSaveState WPObject_wpSaveState
#define ColorPalette_wpRestoreState WPObject_wpRestoreState
#define ColorPalette_wpMenuItemSelected WPObject_wpMenuItemSelected
#define ColorPalette_wpOpen WPObject_wpOpen
#define ColorPalette_wpFilterMenu WPObject_wpFilterMenu
#define ColorPalette_wpModifyMenu WPObject_wpModifyMenu
#define ColorPalette_wpQueryHandle WPObject_wpQueryHandle
#define ColorPalette_wpSaveImmediate WPObject_wpSaveImmediate
#define ColorPalette_wpSetTitle WPObject_wpSetTitle
#define ColorPalette_wpCopyObject WPObject_wpCopyObject
#define ColorPalette_wpMoveObject WPObject_wpMoveObject
#define ColorPalette_wpQueryIcon WPObject_wpQueryIcon
#define ColorPalette_wpQueryIconData WPObject_wpQueryIconData
#define ColorPalette_wpSetIconData WPObject_wpSetIconData
#define ColorPalette_wpDragOver WPObject_wpDragOver
#define ColorPalette_wpReplaceObject WPObject_wpReplaceObject
#define ColorPalette_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define ColorPalette_wpIdentify WPObject_wpIdentify
#define ColorPalette_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define ColorPalette_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define ColorPalette_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define ColorPalette_wpAddSettingsPages WPObject_wpAddSettingsPages
#define ColorPalette_wpAddToObjUseList WPObject_wpAddToObjUseList
#define ColorPalette_wpAllocMem WPObject_wpAllocMem
#define ColorPalette_wpAppendObject WPObject_wpAppendObject
#define ColorPalette_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define ColorPalette_wpClose WPObject_wpClose
#define ColorPalette_wpCnrInsertObject WPObject_wpCnrInsertObject
#define ColorPalette_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define ColorPalette_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define ColorPalette_wpConfirmDelete WPObject_wpConfirmDelete
#define ColorPalette_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define ColorPalette_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define ColorPalette_wpCreateAnother WPObject_wpCreateAnother
#define ColorPalette_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define ColorPalette_wpCreateShadowObject WPObject_wpCreateShadowObject
#define ColorPalette_wpDelete WPObject_wpDelete
#define ColorPalette_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define ColorPalette_wpDisplayHelp WPObject_wpDisplayHelp
#define ColorPalette_wpDisplayMenu WPObject_wpDisplayMenu
#define ColorPalette_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define ColorPalette_wpDraggedOverObject WPObject_wpDraggedOverObject
#define ColorPalette_wpDrop WPObject_wpDrop
#define ColorPalette_wpDroppedOnObject WPObject_wpDroppedOnObject
#define ColorPalette_wpEndConversation WPObject_wpEndConversation
#define ColorPalette_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define ColorPalette_wpFindUseItem WPObject_wpFindUseItem
#define ColorPalette_wpFormatDragItem WPObject_wpFormatDragItem
#define ColorPalette_wpFree WPObject_wpFree
#define ColorPalette_wpFreeMem WPObject_wpFreeMem
#define ColorPalette_wpHide WPObject_wpHide
#define ColorPalette_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define ColorPalette_wpInsertMenuItems WPObject_wpInsertMenuItems
#define ColorPalette_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define ColorPalette_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define ColorPalette_wpPrintObject WPObject_wpPrintObject
#define ColorPalette_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define ColorPalette_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define ColorPalette_wpQueryConfirmations WPObject_wpQueryConfirmations
#define ColorPalette_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define ColorPalette_wpQueryDefaultView WPObject_wpQueryDefaultView
#define ColorPalette_wpQueryDetailsData WPObject_wpQueryDetailsData
#define ColorPalette_wpQueryError WPObject_wpQueryError
#define ColorPalette_wpSetFolder WPObject_wpSetFolder
#define ColorPalette_wpQueryFolder WPObject_wpQueryFolder
#define ColorPalette_wpQueryMinWindow WPObject_wpQueryMinWindow
#define ColorPalette_wpQueryStyle WPObject_wpQueryStyle
#define ColorPalette_wpSetTaskRec WPObject_wpSetTaskRec
#define ColorPalette_wpFindTaskRec WPObject_wpFindTaskRec
#define ColorPalette_wpQueryTitle WPObject_wpQueryTitle
#define ColorPalette_wpRegisterView WPObject_wpRegisterView
#define ColorPalette_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define ColorPalette_wpRender WPObject_wpRender
#define ColorPalette_wpRenderComplete WPObject_wpRenderComplete
#define ColorPalette_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define ColorPalette_wpRestore WPObject_wpRestore
#define ColorPalette_wpRestoreData WPObject_wpRestoreData
#define ColorPalette_wpRestoreLong WPObject_wpRestoreLong
#define ColorPalette_wpRestoreString WPObject_wpRestoreString
#define ColorPalette_wpSaveData WPObject_wpSaveData
#define ColorPalette_wpSaveDeferred WPObject_wpSaveDeferred
#define ColorPalette_wpSaveLong WPObject_wpSaveLong
#define ColorPalette_wpSaveString WPObject_wpSaveString
#define ColorPalette_wpScanSetupString WPObject_wpScanSetupString
#define ColorPalette_wpSetConcurrentView WPObject_wpSetConcurrentView
#define ColorPalette_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define ColorPalette_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define ColorPalette_wpSetDefaultView WPObject_wpSetDefaultView
#define ColorPalette_wpSetError WPObject_wpSetError
#define ColorPalette_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define ColorPalette_wpSetIcon WPObject_wpSetIcon
#define ColorPalette_wpSetMinWindow WPObject_wpSetMinWindow
#define ColorPalette_wpModifyStyle WPObject_wpModifyStyle
#define ColorPalette_wpSwitchTo WPObject_wpSwitchTo
#define ColorPalette_wpViewObject WPObject_wpViewObject
#define ColorPalette_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define ColorPalette_wpUnlockObject WPObject_wpUnlockObject
#define ColorPalette_wpObjectReady WPObject_wpObjectReady
#define ColorPalette_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define ColorPalette_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define ColorPalette_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define ColorPalette_wpIsDeleteable WPObject_wpIsDeleteable
#define ColorPalette_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define ColorPalette_wpSetObjectID WPObject_wpSetObjectID
#define ColorPalette_wpQueryObjectID WPObject_wpQueryObjectID
#define ColorPalette_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define ColorPalette_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define ColorPalette_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define ColorPalette_wpFindViewItem WPObject_wpFindViewItem
#define ColorPalette_wpLockObject WPObject_wpLockObject
#define ColorPalette_wpIsLocked WPObject_wpIsLocked
#define ColorPalette_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define ColorPalette_wpWaitForClose WPObject_wpWaitForClose
#define ColorPalette_wpSetMenuStyle WPObject_wpSetMenuStyle
#define ColorPalette_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define ColorPalette_wpSetStyle WPObject_wpSetStyle
#define ColorPalette_somInit SOMObject_somInit
#define ColorPalette_somUninit SOMObject_somUninit
#define ColorPalette_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define ColorPalette_somDefaultAssign SOMObject_somDefaultAssign
#define ColorPalette_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define ColorPalette_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define ColorPalette_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define ColorPalette_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define ColorPalette_somDefaultVAssign SOMObject_somDefaultVAssign
#define ColorPalette_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define ColorPalette_somFree SOMObject_somFree
#define ColorPalette_somGetClass SOMObject_somGetClass
#define ColorPalette_somGetClassName SOMObject_somGetClassName
#define ColorPalette_somGetSize SOMObject_somGetSize
#define ColorPalette_somIsA SOMObject_somIsA
#define ColorPalette_somIsInstanceOf SOMObject_somIsInstanceOf
#define ColorPalette_somRespondsTo SOMObject_somRespondsTo
#define ColorPalette_somDispatch SOMObject_somDispatch
#define ColorPalette_somClassDispatch SOMObject_somClassDispatch
#define ColorPalette_somCastObj SOMObject_somCastObj
#define ColorPalette_somResetObj SOMObject_somResetObj
#define ColorPalette_somDispatchV SOMObject_somDispatchV
#define ColorPalette_somDispatchL SOMObject_somDispatchL
#define ColorPalette_somDispatchA SOMObject_somDispatchA
#define ColorPalette_somDispatchD SOMObject_somDispatchD
#define ColorPalette_somPrintSelf SOMObject_somPrintSelf
#define ColorPalette_somDumpSelf SOMObject_somDumpSelf
#define ColorPalette_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_ColorPalette_h */

#ifndef SOM_M_ColorPalette_h
#define SOM_M_ColorPalette_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_ColorPalette
#define M_ColorPalette SOMObject
#endif
/*
 *  metaclass
 */
#include <wpclrpal.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_ColorPalette_MajorVersion 0
#define M_ColorPalette_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_ColorPaletteNewClass c
#pragma linkage(c, system)
#define M_ColorPaletteClassData d
#define M_ColorPaletteCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_ColorPalette_classObj M_ColorPaletteClassData.classObject
#define _M_ColorPalette M_ColorPalette_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_ColorPaletteNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_ColorPaletteNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_ColorPaletteClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_ColorPaletteClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_ColorPaletteCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_ColorPaletteCClassData;

/*
 * New and Renew macros for M_ColorPalette
 */
#define M_ColorPaletteNew() \
   ( _M_ColorPalette ? \
	_somNew(_M_ColorPalette) \
	: ( M_ColorPaletteNewClass(\
		M_ColorPalette_MajorVersion, \
		M_ColorPalette_MinorVersion),\
	   _somNew(_M_ColorPalette)))
#define M_ColorPaletteRenew(buf) \
   ( _M_ColorPalette ? \
	_somRenew(_M_ColorPalette, buf) \
	: ( M_ColorPaletteNewClass(\
		M_ColorPalette_MajorVersion, \
		M_ColorPalette_MinorVersion),\
	   _somRenew(_M_ColorPalette, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_ColorPalette_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_ColorPalette_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryStyle
 */
#define M_ColorPalette_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_ColorPalette_wpclsQueryEditString M_WPPalette_wpclsQueryEditString
#define M_ColorPalette_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_ColorPalette_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_ColorPalette_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_ColorPalette_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_ColorPalette_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_ColorPalette_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_ColorPalette_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_ColorPalette_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_ColorPalette_wpclsNew M_WPObject_wpclsNew
#define M_ColorPalette_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_ColorPalette_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_ColorPalette_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_ColorPalette_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_ColorPalette_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_ColorPalette_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_ColorPalette_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_ColorPalette_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_ColorPalette_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_ColorPalette_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_ColorPalette_wpclsSetError M_WPObject_wpclsSetError
#define M_ColorPalette_wpclsQueryError M_WPObject_wpclsQueryError
#define M_ColorPalette_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_ColorPalette_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_ColorPalette_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_ColorPalette_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_ColorPalette_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_ColorPalette_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_ColorPalette_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_ColorPalette_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_ColorPalette_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_ColorPalette_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_ColorPalette_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_ColorPalette_somUninit SOMObject_somUninit
#define M_ColorPalette_somClassReady SOMClass_somClassReady
#define M_ColorPalette_somNew SOMClass_somNew
#define M_ColorPalette_somRenew SOMClass_somRenew
#define M_ColorPalette__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_ColorPalette__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_ColorPalette__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_ColorPalette_somNewNoInit SOMClass_somNewNoInit
#define M_ColorPalette_somRenewNoInit SOMClass_somRenewNoInit
#define M_ColorPalette_somRenewNoZero SOMClass_somRenewNoZero
#define M_ColorPalette_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_ColorPalette_somAllocate SOMClass_somAllocate
#define M_ColorPalette_somDeallocate SOMClass_somDeallocate
#define M_ColorPalette_somInitClass SOMClass_somInitClass
#define M_ColorPalette_somInitMIClass SOMClass_somInitMIClass
#define M_ColorPalette_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_ColorPalette_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_ColorPalette_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_ColorPalette_somGetApplyStub SOMClass_somGetApplyStub
#define M_ColorPalette_somGetClassData SOMClass_somGetClassData
#define M_ColorPalette_somSetClassData SOMClass_somSetClassData
#define M_ColorPalette_somGetClassMtab SOMClass_somGetClassMtab
#define M_ColorPalette_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_ColorPalette_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_ColorPalette_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_ColorPalette_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_ColorPalette_somGetMemberToken SOMClass_somGetMemberToken
#define M_ColorPalette_somGetMethodData SOMClass_somGetMethodData
#define M_ColorPalette_somGetRdStub SOMClass_somGetRdStub
#define M_ColorPalette_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_ColorPalette_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_ColorPalette_somGetMethodToken SOMClass_somGetMethodToken
#define M_ColorPalette_somGetName SOMClass_somGetName
#define M_ColorPalette_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_ColorPalette_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_ColorPalette_somGetNumMethods SOMClass_somGetNumMethods
#define M_ColorPalette_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_ColorPalette_somGetParent SOMClass_somGetParent
#define M_ColorPalette_somGetParents SOMClass_somGetParents
#define M_ColorPalette_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_ColorPalette_somFindMethod SOMClass_somFindMethod
#define M_ColorPalette_somFindMethodOk SOMClass_somFindMethodOk
#define M_ColorPalette_somFindSMethod SOMClass_somFindSMethod
#define M_ColorPalette_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_ColorPalette_somLookupMethod SOMClass_somLookupMethod
#define M_ColorPalette_somCheckVersion SOMClass_somCheckVersion
#define M_ColorPalette_somDescendedFrom SOMClass_somDescendedFrom
#define M_ColorPalette_somSupportsMethod SOMClass_somSupportsMethod
#define M_ColorPalette_somDefinedMethod SOMClass_somDefinedMethod
#define M_ColorPalette_somOverrideMtab SOMClass_somOverrideMtab
#define M_ColorPalette_somDefaultInit SOMObject_somDefaultInit
#define M_ColorPalette_somDestruct SOMObject_somDestruct
#define M_ColorPalette_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_ColorPalette_somDefaultAssign SOMObject_somDefaultAssign
#define M_ColorPalette_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_ColorPalette_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_ColorPalette_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_ColorPalette_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_ColorPalette_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_ColorPalette_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_ColorPalette_somInit SOMObject_somInit
#define M_ColorPalette_somFree SOMObject_somFree
#define M_ColorPalette_somGetClass SOMObject_somGetClass
#define M_ColorPalette_somGetClassName SOMObject_somGetClassName
#define M_ColorPalette_somGetSize SOMObject_somGetSize
#define M_ColorPalette_somIsA SOMObject_somIsA
#define M_ColorPalette_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_ColorPalette_somRespondsTo SOMObject_somRespondsTo
#define M_ColorPalette_somDispatch SOMObject_somDispatch
#define M_ColorPalette_somClassDispatch SOMObject_somClassDispatch
#define M_ColorPalette_somCastObj SOMObject_somCastObj
#define M_ColorPalette_somResetObj SOMObject_somResetObj
#define M_ColorPalette_somDispatchV SOMObject_somDispatchV
#define M_ColorPalette_somDispatchL SOMObject_somDispatchL
#define M_ColorPalette_somDispatchA SOMObject_somDispatchA
#define M_ColorPalette_somDispatchD SOMObject_somDispatchD
#define M_ColorPalette_somPrintSelf SOMObject_somPrintSelf
#define M_ColorPalette_somDumpSelf SOMObject_somDumpSelf
#define M_ColorPalette_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_ColorPalette_h */
