
/*
 * This file was generated by the SOM Compiler.
 * FileName: h\clrstar.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * clrstar.idl - StarColorPalette interface definition.
 * 
 * Converted from the SOM 1.0 precompiler format (CLRSTAR.SC, produced by
 * 'spc' 1.22 / 'emitcsc' 1.10) to SOM IDL for the modern SOM compiler (sc).
 * 
 * Original class:
 *   IBM Corporation, 1992/1993 - Named Color Palette WPS sample.
 *   StarColorPalette = minimal illustration of a palette subclass: it only
 *   overrides QuerySampleShape so each color swatch is drawn as a star
 *   instead of a rectangle.
 * 
 * Conversion notes (full story in README.md):
 *   - 'class:'/'parent:' syntax -> 'interface X : Parent'
 *   - 'override QuerySampleShape;' -> 'QuerySampleShape: override;'
 *     inside the implementation block
 *   - no metaclass overrides exist (as in the original, whose DEF noted
 *     'SOM didn't give us a metaclass'); modern sc nevertheless emits
 *     M_StarColorPalette bindings for the implicit metaclass - they are
 *     exported for completeness.
 *   - C.ih passthru content (SOM_NoTest/_RETAIL defines, PM prelude) moved
 *     to the top of src\clrstar.c
 */


#ifndef SOM_StarColorPalette_h
#define SOM_StarColorPalette_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef StarColorPalette
#define StarColorPalette SOMObject
#endif
#include <clrpalet.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_WPPalette
    #define M_WPPalette SOMObject
#endif /* M_WPPalette */
#ifndef M_WPColorPalette
    #define M_WPColorPalette SOMObject
#endif /* M_WPColorPalette */
#ifndef M_ColorPalette
    #define M_ColorPalette SOMObject
#endif /* M_ColorPalette */

/*
 * End of bindings for IDL types.
 */

#define StarColorPalette_MajorVersion 1
#define StarColorPalette_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define StarColorPaletteNewClass c
#pragma linkage(c, system)
#define StarColorPaletteClassData d
#define StarColorPaletteCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define StarColorPalette_classObj StarColorPaletteClassData.classObject
#define _StarColorPalette StarColorPalette_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK StarColorPaletteNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(StarColorPaletteNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct StarColorPaletteClassDataStructure {
	SOMClass *classObject;
} SOMDLINK StarColorPaletteClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct StarColorPaletteCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK StarColorPaletteCClassData;

/*
 * New and Renew macros for StarColorPalette
 */
#define StarColorPaletteNew() \
   ( _StarColorPalette ? \
	_somNew(_StarColorPalette) \
	: ( StarColorPaletteNewClass(\
		StarColorPalette_MajorVersion, \
		StarColorPalette_MinorVersion),\
	   _somNew(_StarColorPalette)))
#define StarColorPaletteRenew(buf) \
   ( _StarColorPalette ? \
	_somRenew(_StarColorPalette, buf) \
	: ( StarColorPaletteNewClass(\
		StarColorPalette_MajorVersion, \
		StarColorPalette_MinorVersion),\
	   _somRenew(_StarColorPalette, buf)))

/*
 * Override method: QuerySampleShape
 */
#define StarColorPalette_QuerySampleShape(somSelf,pPoints,pcPoints) \
	ColorPalette_QuerySampleShape(somSelf,pPoints,pcPoints)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define StarColorPalette_SetEditDlgHandle ColorPalette_SetEditDlgHandle
#define StarColorPalette_QueryEditDlgHandle ColorPalette_QueryEditDlgHandle
#define StarColorPalette_wpPaintCell WPPalette_wpPaintCell
#define StarColorPalette_wpEditCell WPPalette_wpEditCell
#define StarColorPalette_wpRedrawCell WPPalette_wpRedrawCell
#define StarColorPalette_wpSetup WPObject_wpSetup
#define StarColorPalette_wpSelectCell WPPalette_wpSelectCell
#define StarColorPalette_wpDragCell WPPalette_wpDragCell
#define StarColorPalette_wpQueryPaletteHelp WPPalette_wpQueryPaletteHelp
#define StarColorPalette_wpSetupOnce WPObject_wpSetupOnce
#define StarColorPalette_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define StarColorPalette_wpInitData WPObject_wpInitData
#define StarColorPalette_somDefaultInit SOMObject_somDefaultInit
#define StarColorPalette_somDestruct SOMObject_somDestruct
#define StarColorPalette_wpSetupCell WPPalette_wpSetupCell
#define StarColorPalette_wpQueryPaletteInfo WPPalette_wpQueryPaletteInfo
#define StarColorPalette_wpSetPaletteInfo WPPalette_wpSetPaletteInfo
#define StarColorPalette_wpPaintPalette WPPalette_wpPaintPalette
#define StarColorPalette_wpInitCellStructs WPPalette_wpInitCellStructs
#define StarColorPalette_wpSaveCellData WPPalette_wpSaveCellData
#define StarColorPalette_wpRestoreCellData WPPalette_wpRestoreCellData
#define StarColorPalette_wpFreeCellData WPPalette_wpFreeCellData
#define StarColorPalette_wpUnInitData WPObject_wpUnInitData
#define StarColorPalette_wpSaveState WPObject_wpSaveState
#define StarColorPalette_wpRestoreState WPObject_wpRestoreState
#define StarColorPalette_wpMenuItemSelected WPObject_wpMenuItemSelected
#define StarColorPalette_wpOpen WPObject_wpOpen
#define StarColorPalette_wpFilterMenu WPObject_wpFilterMenu
#define StarColorPalette_wpModifyMenu WPObject_wpModifyMenu
#define StarColorPalette_wpQueryHandle WPObject_wpQueryHandle
#define StarColorPalette_wpSaveImmediate WPObject_wpSaveImmediate
#define StarColorPalette_wpSetTitle WPObject_wpSetTitle
#define StarColorPalette_wpCopyObject WPObject_wpCopyObject
#define StarColorPalette_wpMoveObject WPObject_wpMoveObject
#define StarColorPalette_wpQueryIcon WPObject_wpQueryIcon
#define StarColorPalette_wpQueryIconData WPObject_wpQueryIconData
#define StarColorPalette_wpSetIconData WPObject_wpSetIconData
#define StarColorPalette_wpDragOver WPObject_wpDragOver
#define StarColorPalette_wpReplaceObject WPObject_wpReplaceObject
#define StarColorPalette_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define StarColorPalette_wpIdentify WPObject_wpIdentify
#define StarColorPalette_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define StarColorPalette_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define StarColorPalette_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define StarColorPalette_wpAddSettingsPages WPObject_wpAddSettingsPages
#define StarColorPalette_wpAddToObjUseList WPObject_wpAddToObjUseList
#define StarColorPalette_wpAllocMem WPObject_wpAllocMem
#define StarColorPalette_wpAppendObject WPObject_wpAppendObject
#define StarColorPalette_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define StarColorPalette_wpClose WPObject_wpClose
#define StarColorPalette_wpCnrInsertObject WPObject_wpCnrInsertObject
#define StarColorPalette_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define StarColorPalette_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define StarColorPalette_wpConfirmDelete WPObject_wpConfirmDelete
#define StarColorPalette_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define StarColorPalette_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define StarColorPalette_wpCreateAnother WPObject_wpCreateAnother
#define StarColorPalette_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define StarColorPalette_wpCreateShadowObject WPObject_wpCreateShadowObject
#define StarColorPalette_wpDelete WPObject_wpDelete
#define StarColorPalette_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define StarColorPalette_wpDisplayHelp WPObject_wpDisplayHelp
#define StarColorPalette_wpDisplayMenu WPObject_wpDisplayMenu
#define StarColorPalette_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define StarColorPalette_wpDraggedOverObject WPObject_wpDraggedOverObject
#define StarColorPalette_wpDrop WPObject_wpDrop
#define StarColorPalette_wpDroppedOnObject WPObject_wpDroppedOnObject
#define StarColorPalette_wpEndConversation WPObject_wpEndConversation
#define StarColorPalette_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define StarColorPalette_wpFindUseItem WPObject_wpFindUseItem
#define StarColorPalette_wpFormatDragItem WPObject_wpFormatDragItem
#define StarColorPalette_wpFree WPObject_wpFree
#define StarColorPalette_wpFreeMem WPObject_wpFreeMem
#define StarColorPalette_wpHide WPObject_wpHide
#define StarColorPalette_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define StarColorPalette_wpInsertMenuItems WPObject_wpInsertMenuItems
#define StarColorPalette_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define StarColorPalette_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define StarColorPalette_wpPrintObject WPObject_wpPrintObject
#define StarColorPalette_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define StarColorPalette_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define StarColorPalette_wpQueryConfirmations WPObject_wpQueryConfirmations
#define StarColorPalette_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define StarColorPalette_wpQueryDefaultView WPObject_wpQueryDefaultView
#define StarColorPalette_wpQueryDetailsData WPObject_wpQueryDetailsData
#define StarColorPalette_wpQueryError WPObject_wpQueryError
#define StarColorPalette_wpSetFolder WPObject_wpSetFolder
#define StarColorPalette_wpQueryFolder WPObject_wpQueryFolder
#define StarColorPalette_wpQueryMinWindow WPObject_wpQueryMinWindow
#define StarColorPalette_wpQueryStyle WPObject_wpQueryStyle
#define StarColorPalette_wpSetTaskRec WPObject_wpSetTaskRec
#define StarColorPalette_wpFindTaskRec WPObject_wpFindTaskRec
#define StarColorPalette_wpQueryTitle WPObject_wpQueryTitle
#define StarColorPalette_wpRegisterView WPObject_wpRegisterView
#define StarColorPalette_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define StarColorPalette_wpRender WPObject_wpRender
#define StarColorPalette_wpRenderComplete WPObject_wpRenderComplete
#define StarColorPalette_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define StarColorPalette_wpRestore WPObject_wpRestore
#define StarColorPalette_wpRestoreData WPObject_wpRestoreData
#define StarColorPalette_wpRestoreLong WPObject_wpRestoreLong
#define StarColorPalette_wpRestoreString WPObject_wpRestoreString
#define StarColorPalette_wpSaveData WPObject_wpSaveData
#define StarColorPalette_wpSaveDeferred WPObject_wpSaveDeferred
#define StarColorPalette_wpSaveLong WPObject_wpSaveLong
#define StarColorPalette_wpSaveString WPObject_wpSaveString
#define StarColorPalette_wpScanSetupString WPObject_wpScanSetupString
#define StarColorPalette_wpSetConcurrentView WPObject_wpSetConcurrentView
#define StarColorPalette_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define StarColorPalette_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define StarColorPalette_wpSetDefaultView WPObject_wpSetDefaultView
#define StarColorPalette_wpSetError WPObject_wpSetError
#define StarColorPalette_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define StarColorPalette_wpSetIcon WPObject_wpSetIcon
#define StarColorPalette_wpSetMinWindow WPObject_wpSetMinWindow
#define StarColorPalette_wpModifyStyle WPObject_wpModifyStyle
#define StarColorPalette_wpSwitchTo WPObject_wpSwitchTo
#define StarColorPalette_wpViewObject WPObject_wpViewObject
#define StarColorPalette_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define StarColorPalette_wpUnlockObject WPObject_wpUnlockObject
#define StarColorPalette_wpObjectReady WPObject_wpObjectReady
#define StarColorPalette_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define StarColorPalette_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define StarColorPalette_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define StarColorPalette_wpIsDeleteable WPObject_wpIsDeleteable
#define StarColorPalette_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define StarColorPalette_wpSetObjectID WPObject_wpSetObjectID
#define StarColorPalette_wpQueryObjectID WPObject_wpQueryObjectID
#define StarColorPalette_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define StarColorPalette_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define StarColorPalette_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define StarColorPalette_wpFindViewItem WPObject_wpFindViewItem
#define StarColorPalette_wpLockObject WPObject_wpLockObject
#define StarColorPalette_wpIsLocked WPObject_wpIsLocked
#define StarColorPalette_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define StarColorPalette_wpWaitForClose WPObject_wpWaitForClose
#define StarColorPalette_wpSetMenuStyle WPObject_wpSetMenuStyle
#define StarColorPalette_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define StarColorPalette_wpSetStyle WPObject_wpSetStyle
#define StarColorPalette_somInit SOMObject_somInit
#define StarColorPalette_somUninit SOMObject_somUninit
#define StarColorPalette_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define StarColorPalette_somDefaultAssign SOMObject_somDefaultAssign
#define StarColorPalette_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define StarColorPalette_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define StarColorPalette_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define StarColorPalette_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define StarColorPalette_somDefaultVAssign SOMObject_somDefaultVAssign
#define StarColorPalette_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define StarColorPalette_somFree SOMObject_somFree
#define StarColorPalette_somGetClass SOMObject_somGetClass
#define StarColorPalette_somGetClassName SOMObject_somGetClassName
#define StarColorPalette_somGetSize SOMObject_somGetSize
#define StarColorPalette_somIsA SOMObject_somIsA
#define StarColorPalette_somIsInstanceOf SOMObject_somIsInstanceOf
#define StarColorPalette_somRespondsTo SOMObject_somRespondsTo
#define StarColorPalette_somDispatch SOMObject_somDispatch
#define StarColorPalette_somClassDispatch SOMObject_somClassDispatch
#define StarColorPalette_somCastObj SOMObject_somCastObj
#define StarColorPalette_somResetObj SOMObject_somResetObj
#define StarColorPalette_somDispatchV SOMObject_somDispatchV
#define StarColorPalette_somDispatchL SOMObject_somDispatchL
#define StarColorPalette_somDispatchA SOMObject_somDispatchA
#define StarColorPalette_somDispatchD SOMObject_somDispatchD
#define StarColorPalette_somPrintSelf SOMObject_somPrintSelf
#define StarColorPalette_somDumpSelf SOMObject_somDumpSelf
#define StarColorPalette_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_StarColorPalette_h */
